default:
  graphformat: pdf
#  font: DejaVu Serif
#  mono: DejaVu Sans Mono
  font: Latin Modern Roman
#  mono: Latin Modern Mono
  mono: Courier

  title: "HSZ-T Software-Projekt: Fraktale"
  titleshort: "Fraktale"
  author: "Sandra Freihofer, Daniel Ritz"
  authorshort: "S.Freihofer, D.Ritz"

  lang: "de"
  langrule: "\\frenchspacing"
  hyphrule: "\\usepackage[ngerman]{babel}"
  chaptername: "Kapitel "
  appendixname: "Anhang "
  postchap: ""
  presect: "Abschnitt "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Inhalt"
  fig: "Abbildung "
  tab: "Tabelle "
  indent: "\\qquad"
