default:
  graphformat: pdf
#  font: Helvetica
#  font: Bookman Old Style
#  font: DejaVu Serif
  font: Latin Modern Roman
#  bold: "{* Bold}"
#  mono: Andale Mono
#  mono: DejaVu Sans Mono
  mono: Latin Modern Mono

  title: "HSZ-T Software-Projekt: Fraktale"
  author: "Sandra Freihofer, Daniel Ritz"

  chaptername: "Kapitel "
  appendixname: "Anhang "
  postchap: ""
  presect: "Abschnitt "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Inhalt"
  fig: "Abbildung "
  tab: "Tabelle "
  indent: "\\qquad"
